build: compile
	g++ draw_stick_diagram.o -o draw_stick_diagram.exe -L "C:\Library\SFML\lib" -lsfml-graphics -lsfml-window -lsfml-system
compile:
	g++ -c draw_stick_diagram.cpp -I "C:\Library\SFML\include"